<?php
/** Static release contract for Research Librarian AI v7.7.0 Global Library Discovery & Federated Research. */
$root = dirname( __DIR__ );
$main = file_get_contents( $root . '/sustainable-catalyst-research-librarian-ai.php' );
$module = file_get_contents( $root . '/includes/class-sc-rl-v700-connected-platform.php' );
$backend = file_get_contents( $root . '/backend/app/main.py' );
$models = file_get_contents( $root . '/backend/app/models.py' );
$federation = file_get_contents( $root . '/backend/app/federated_discovery.py' );
$state = file_get_contents( $root . '/backend/app/research_state.py' );
$platform = file_get_contents( $root . '/backend/app/platform_v7.py' );
$store = file_get_contents( $root . '/backend/app/store.py' );
$js = file_get_contents( $root . '/assets/sc-research-platform-v770-federation.js' );
$css = file_get_contents( $root . '/assets/sc-research-librarian-ai.css' );
$docs = file_get_contents( $root . '/docs/V770_GLOBAL_LIBRARY_DISCOVERY_FEDERATED_RESEARCH.md' );
$manifest = json_decode( file_get_contents( $root . '/data/research_librarian_federated_discovery_manifest_v7.7.0.json' ), true );
$v760 = json_decode( file_get_contents( $root . '/data/research_librarian_workspace_promotion_manifest_v7.6.0.json' ), true );
$migrations = glob( $root . '/backend/migrations/*.sql' );
$checks = array(
  'version_header' => false !== strpos($main,'Version: 9.1.0'),
  'version_constant' => false !== strpos($main,"const VERSION        = '9.1.0';"),
  'backend_version' => false !== strpos(file_get_contents($root.'/backend/app/__init__.py'),'__version__ = "9.1.0"'),
  'module_version' => false !== strpos($module,"const VERSION = '8.0.0';"),
  'api_16' => false !== strpos($platform,'sc-connected-research-api/2.0'),
  'workspace_26' => false !== strpos($module,'sc-research-librarian-public-workspace/3.0'),
  'sqlite_schema_17' => false !== strpos($store,'SCHEMA_VERSION = 19'),
  'knowledge_index_13' => false !== strpos($store,'sc-research-librarian-knowledge-index/13.0'),
  'no_new_postgres_migration' => is_file($root . '/backend/migrations/004_async_document_processing_runtime.sql'),
  'federated_module' => file_exists($root.'/backend/app/federated_discovery.py'),
  'provider_catalog_schema' => false !== strpos($federation,'sc-federated-provider-catalog/1.0'),
  'search_schema' => false !== strpos($federation,'sc-federated-research-search/1.0'),
  'result_schema' => false !== strpos($federation,'sc-federated-research-result/1.0'),
  'import_schema' => false !== strpos($federation,'sc-federated-library-import/1.0'),
  'openalex_provider' => false !== strpos($federation,'"openalex"'),
  'crossref_provider' => false !== strpos($federation,'"crossref"'),
  'europe_pmc_provider' => false !== strpos($federation,'"europe-pmc"'),
  'open_library_provider' => false !== strpos($federation,'"open-library"'),
  'arxiv_provider' => false !== strpos($federation,'"arxiv"'),
  'openalex_base_fixed' => false !== strpos($federation,'https://api.openalex.org'),
  'crossref_base_fixed' => false !== strpos($federation,'https://api.crossref.org'),
  'europe_pmc_base_fixed' => false !== strpos($federation,'https://www.ebi.ac.uk/europepmc/webservices/rest'),
  'open_library_base_fixed' => false !== strpos($federation,'https://openlibrary.org'),
  'arxiv_base_fixed' => false !== strpos($federation,'https://export.arxiv.org'),
  'normalizer_openalex' => false !== strpos($federation,'def normalize_openalex('),
  'normalizer_crossref' => false !== strpos($federation,'def normalize_crossref('),
  'normalizer_europe_pmc' => false !== strpos($federation,'def normalize_europe_pmc('),
  'normalizer_open_library' => false !== strpos($federation,'def normalize_open_library('),
  'normalizer_arxiv' => false !== strpos($federation,'def normalize_arxiv('),
  'dedupe' => false !== strpos($federation,'def deduplicate_results('),
  'doi_key' => false !== strpos($federation,'return "doi:"'),
  'arxiv_key' => false !== strpos($federation,'return "arxiv:"'),
  'isbn_key' => false !== strpos($federation,'return "isbn:"'),
  'provider_identity_preserved' => false !== strpos($federation,'"provider_identity_preserved": True'),
  'external_only' => false !== strpos($federation,'"external_discovery_only": True'),
  'not_editorial' => false !== strpos($federation,'"not_sustainable_catalyst_editorial": True'),
  'not_verified' => false !== strpos($federation,'"not_verified_evidence": True'),
  'explicit_save' => false !== strpos($federation,'"explicit_save_required": True'),
  'external_reference_import' => false !== strpos($federation,'"source_scope": "external-reference"'),
  'private_import' => false !== strpos($federation,'"visibility": "private"'),
  'search_request_model' => false !== strpos($models,'class FederatedSearchRequest'),
  'save_request_model' => false !== strpos($models,'class FederatedResultSaveRequest'),
  'search_table' => false !== strpos($store,'CREATE TABLE IF NOT EXISTS research_federated_searches'),
  'search_owner_index' => false !== strpos($store,'idx_federated_searches_owner'),
  'save_search_method' => false !== strpos($store,'def save_federated_search('),
  'get_search_method' => false !== strpos($store,'def federated_search('),
  'list_search_method' => false !== strpos($store,'def federated_searches('),
  'backup_searches' => false !== strpos($store,'"federated_searches":federated_searches'),
  'summary_searches' => false !== strpos($store,'"federated_searches":"research_federated_searches"'),
  'provider_endpoint' => false !== strpos($backend,'@app.get("/v1/federation/providers"'),
  'history_endpoint' => false !== strpos($backend,'@app.get("/v1/federation/searches"'),
  'search_endpoint' => false !== strpos($backend,'@app.post("/v1/federation/search"'),
  'save_endpoint' => false !== strpos($backend,'@app.post("/v1/federation/searches/{search_id}/results/{result_id}/save"'),
  'stored_snapshot_import' => false !== strpos($backend,'result = next((item for item in list(search.get("results") or [])'),
  'owner_enforced_backend' => false !== strpos($backend,'Federated search does not belong to this owner.'),
  'activity_search' => false !== strpos($state,'"federated-search"'),
  'activity_saved' => false !== strpos($state,'"federated-result-saved"'),
  'wp_provider_schema' => false !== strpos($module,"const FEDERATED_PROVIDER_SCHEMA = 'sc-federated-provider-catalog/1.0';"),
  'wp_search_schema' => false !== strpos($module,"const FEDERATED_SEARCH_SCHEMA = 'sc-federated-research-search/1.0';"),
  'wp_import_schema' => false !== strpos($module,"const FEDERATED_IMPORT_SCHEMA = 'sc-federated-library-import/1.0';"),
  'wp_capability' => false !== strpos($module,"'federated_discovery' => '1'"),
  'wp_provider_route' => false !== strpos($module,"'/platform/v7/federation/providers'"),
  'wp_search_route' => false !== strpos($module,"'/platform/v7/federation/searches'"),
  'wp_save_route' => false !== strpos($module,"/results/(?P<result_id>"),
  'wp_owner_server_side' => false !== strpos($module, '\'owner_ref\' => $scope[\'owner_ref\']'),
  'wp_context_authorized' => false !== strpos($module,'self::authorized_context( $context_id )'),
  'wp_project_authorized' => false !== strpos($module,'self::authorized_project( $project_id, false )'),
  'wp_search_owner_recheck' => false !== strpos($module,"'?owner_ref=' . rawurlencode( self::owner_ref() )"),
  'wp_provider_selection_required' => false !== strpos($module,'Choose at least one supported external provider.'),
  'js_provider_selection_required' => false !== strpos($js,'Choose at least one external provider.'),
  'wp_provider_allowlist' => false !== strpos($module,"array( 'openalex', 'crossref', 'europe-pmc', 'open-library', 'arxiv' )"),
  'wp_asset' => false !== strpos($module,'sc-research-platform-v770-federation.js'),
  'wp_button' => false !== strpos($module,'data-sc-rl-v770-federation-run>Discover globally'),
  'wp_panel' => false !== strpos($module,'data-sc-rl-v770-federation-panel'),
  'js_search' => false !== strpos($js,"request('federation/searches'"),
  'js_save' => false !== strpos($js,'Save to My Library'),
  'js_provider_badges' => false !== strpos($js,'sc-rl-v770-provider-badges'),
  'js_partial_failure' => false !== strpos($js,'Partial results remain visible'),
  'js_boundary' => false !== strpos($js,'does not create editorial approval or a truth judgment'),
  'css_panel' => false !== strpos($css,'.sc-rl-v770-federation-panel'),
  'css_result' => false !== strpos($css,'.sc-rl-v770-result'),
  'manifest_version' => is_array($manifest) && '7.7.0' === ($manifest['version']??''),
  'manifest_api' => is_array($manifest) && 'sc-connected-research-api/1.6' === ($manifest['api_schema']??''),
  'manifest_workspace' => is_array($manifest) && 'sc-research-librarian-public-workspace/2.6' === ($manifest['workspace_schema']??''),
  'manifest_sqlite' => is_array($manifest) && 17 === ($manifest['storage']['ancillary_sqlite_schema_version']??0),
  'manifest_no_neon' => is_array($manifest) && false === ($manifest['storage']['new_postgres_migration_required']??true),
  'manifest_fixed_allowlist' => is_array($manifest) && true === ($manifest['discovery']['fixed_provider_allowlist']??false),
  'manifest_arbitrary_forbidden' => is_array($manifest) && true === ($manifest['discovery']['arbitrary_remote_urls_forbidden']??false),
  'manifest_explicit_save' => is_array($manifest) && true === ($manifest['governance']['explicit_save_to_library_required']??false),
  'manifest_scope' => is_array($manifest) && 'external-reference' === ($manifest['governance']['saved_source_scope']??''),
  'manifest_query_disclosure' => is_array($manifest) && true === ($manifest['privacy_boundaries']['query_terms_sent_to_selected_external_providers']??false) && true === ($manifest['privacy_boundaries']['wordpress_user_identity_not_forwarded_to_providers']??false),
  'ui_query_disclosure' => false !== strpos($module,'Search terms are sent to the external providers you select'),
  'manifest_snapshot_boundary' => is_array($manifest) && true === ($manifest['privacy_boundaries']['browser_cannot_submit_arbitrary_result_payload_for_import']??false),
  'manifest_backup' => is_array($manifest) && true === ($manifest['backup']['federated_searches_included']??false),
  'v760_manifest_preserved' => is_array($v760) && '7.6.0' === ($v760['version']??'') && 16 === ($v760['storage']['ancillary_sqlite_schema_version']??0),
  'docs_external_boundary' => false !== strpos($docs,'**not** a Sustainable Catalyst editorial recommendation'),
  'docs_snapshot_boundary' => false !== strpos($docs,'browser does not send an arbitrary source payload'),
  'docs_no_neon' => false !== strpos($docs,'No Neon/Postgres knowledge-index migration is required for v7.7.0'),
);
$failed=array_keys(array_filter($checks,static function($value){return !$value;}));
echo json_encode(array('version'=>'7.7.0','checks'=>$checks,'passed'=>count($checks)-count($failed),'failed'=>count($failed),'failures'=>$failed),JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES).PHP_EOL;
exit($failed?1:0);
